name: Website Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: HTML5 Validation
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        css: true
        extra: --ignore-re "Obsolete doctype|xml:lang.*lang|summary.*obsolete|valign.*obsolete|tt.*obsolete|frameborder.*obsolete|marginwidth.*obsolete|marginheight.*obsolete|scrolling.*obsolete|align.*obsolete"
        
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.8.0
      with:
        args: --verbose --no-progress --accept 200,204,403,429 --timeout 10 --exclude-all-private --exclude '.*jemdoc\.jaboc\.net.*' --exclude '.*people\.engr\.ncsu\.edu.*' --exclude '.*www4\.ncsu\.edu.*' --exclude '.*patft.*\.uspto\.gov.*' --exclude '.*scholar\.google\.com.*' --exclude '.*upatras\.gr.*' --exclude '.*telemedicine\.upatras\.gr.*' --exclude '.*wltl\.ee\.upatras\.gr.*' --exclude '.*atg\.netapp\.com.*' --exclude '.*nrgp\.ncsu\.edu.*' --exclude '.*nprg\.ncsu\.edu.*' --exclude 'file:///.*/(includes/|teach/)[^/]*$' --exclude 'file:///.*/(defaultcss|infoblockcontent|len\(.*\)|StringIO|OPTIONS|SOURCEFILE|analytics|bodystart|bodyend|blocktitle|blocks|codeblock.*|currentmenuitem|doctitle.*|firstbit|footerstart|footerend|infoblock.*|lastupdated|menu.*|nomenu|sourcelink|specificcss|specificjs|subtitle|tag|windowtitle|fwtitle.*|:-1|:5|0|2:|4:)$' './**/*.html'
        fail: false
        
    - name: Check for broken PDF links
      run: |
        echo "Checking for missing PDF files referenced in HTML..."
        for file in *.html includes/*.html teach/*.html; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            # Extract PDF links and check if files exist
            grep -oP 'href="[^"]*\.pdf"' "$file" | sed 's/href="//;s/"//' | while read -r link; do
              if [[ "$link" =~ ^http ]]; then
                echo "  External PDF: $link (skipping local check)"
              elif [ ! -f "$link" ]; then
                echo "  ERROR: Missing PDF file: $link"
                exit 1
              else
                echo "  OK: $link"
              fi
            done
          fi
        done
        
    - name: Check for missing image files
      run: |
        echo "Checking for missing image files..."
        for file in *.html includes/*.html teach/*.html; do
          if [ -f "$file" ]; then
            echo "Checking images in $file..."
            # Get the directory of the current file
            dir=$(dirname "$file")
            # Extract image src attributes
            grep -oP 'src="[^"]*\.(jpg|jpeg|png|gif|JPG|JPEG|PNG|GIF)"' "$file" | sed 's/src="//;s/"//' | while read -r img; do
              if [[ "$img" =~ ^http ]]; then
                echo "  External image: $img (skipping local check)"
              else
                # Resolve relative path based on the file's directory
                if [[ "$img" =~ ^/ ]]; then
                  # Absolute path
                  img_path="$img"
                else
                  # Relative path - resolve relative to the file's directory
                  img_path="$dir/$img"
                fi
                
                if [ ! -f "$img_path" ]; then
                  echo "  ERROR: Missing image file: $img_path (referenced as $img in $file)"
                  exit 1
                else
                  echo "  OK: $img_path"
                fi
              fi
            done
          fi
        done
        
    - name: Check HTML structure consistency
      run: |
        echo "Checking HTML structure consistency..."
        # Check if all HTML files have proper DOCTYPE
        for file in *.html includes/*.html teach/*.html; do
          if [ -f "$file" ]; then
            if ! grep -q "<!DOCTYPE" "$file"; then
              echo "ERROR: $file is missing DOCTYPE declaration"
              exit 1
            fi
          fi
        done
        
        # Check for consistent navigation menu
        echo "Checking navigation menu consistency..."
        menu_items=("index.html" "publication.html" "patents.html" "teach.html" "experience.html" "awards.html" "service.html" "talks.html" "students.html")
        
        for file in *.html; do
          if [ -f "$file" ] && [ "$file" != "other.html" ]; then
            for item in "${menu_items[@]}"; do
              if ! grep -q "href=\"$item\"" "$file"; then
                echo "WARNING: $file may be missing navigation link to $item"
              fi
            done
          fi
        done
        
    - name: Check for potential security issues
      run: |
        echo "Checking for potential security issues..."
        # Check for any potential XSS vulnerabilities (basic check)
        if grep -r "javascript:" *.html includes/*.html teach/*.html 2>/dev/null; then
          echo "WARNING: Found javascript: URLs which could be security risks"
        fi
        
        # Check for any embedded scripts
        if grep -r "<script" *.html includes/*.html teach/*.html 2>/dev/null; then
          echo "INFO: Found embedded scripts - review for security"
        fi
        
        echo "Security check completed"